### ISSUE TITLE
build Perl 5.36.3 on Darwin fails

### ISSUE THREAD

**Issue by shogo82148** [bingos/devel-patchperl#68]
After upgrading Devel::PatchPerl from v2.08 to v2.14, building Perl 5.36.3 on Darwin has started to fail.

```plain
% patchperl --version
Devel::PatchPerl 2.14
```

```plain
% clang --version
Apple clang version 17.0.0 (clang-1700.4.4.1)
Target: arm64-apple-darwin25.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

build log:

```plain
% curl -sSL https://cpan.metacpan.org/authors/id/P/PE/PEVANS/perl-5.36.3.tar.gz
% tar xzvf perl-5.36.3.tar.gz
% cd perl-5.36.3
% patchperl
% ./Configure -des
% make
(snip)

  util.c:2516:30: error: call to undeclared function 'S_env_alloc'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   2516 |             tmpenv = (char**)S_env_alloc(NULL, max, 2, 0, sizeof(char*));
        |                              ^
  util.c:2516:30: note: did you mean 'S_mess_alloc'?
  util.c:1494:1: note: 'S_mess_alloc' declared here
   1494 | S_mess_alloc(pTHX)
        | ^
  util.c:2516:22: warning: cast to 'char **' from smaller integer type 'int' [-Wint-to-pointer-cast]
   2516 |             tmpenv = (char**)S_env_alloc(NULL, max, 2, 0, sizeof(char*));
        |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  util.c:2520:27: error: incompatible integer to pointer conversion assigning to 'char *' from 'int' [-Wint-conversion]
   2520 |                 tmpenv[j] = S_env_alloc(NULL, len, 1, 0, 1);
        |                           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  util.c:2542:31: error: call to undeclared function 'S_env_alloc'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   2542 |             environ = (char**)S_env_alloc(environ, i, 2, 0, sizeof(char*));
        |                               ^
  util.c:2542:23: warning: cast to 'char **' from smaller integer type 'int' [-Wint-to-pointer-cast]
   2542 |             environ = (char**)S_env_alloc(environ, i, 2, 0, sizeof(char*));
        |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  util.c:2550:22: error: call to undeclared function 'S_env_alloc'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   2550 |         environ[i] = S_env_alloc(NULL, nlen, vlen, 2, 1);
        |                      ^
  util.c:2550:20: error: incompatible integer to pointer conversion assigning to 'char *' from 'int' [-Wint-conversion]
   2550 |         environ[i] = S_env_alloc(NULL, nlen, vlen, 2, 1);
        |                    ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  2 warnings and 5 errors generated.
  make: *** [util.o] Error 1
```
